### PR TITLE
md fixes

### PR DESCRIPTION
**Pull request by scttcper**

### CODE REVIEW

**Comment by russplaysguitar** [comment]
change that to: `export LUA_CPATH=$LUA_CPATH";$PWD/.libs/?.so"`

**Comment by nmtadam** [comment]
Line 70 is not correct, should have only one backtick at the end of the line.

**Comment by nmtadam** [comment]
Try line 71 without the final backslash.

**Comment by nmtadam** [comment]
From an email exchange I had with  @noahdesu last night:

Some notes. I think we want to avoid duplicating documentation at Ceph.com/docs so we don't have to synchronize with their changes. In the Dependencies section we can change 'ceph' to 'librados-dev', and add a note that Lua-RADOS requires a functioning Ceph cluster. Then make Lua-rados Installation the next section.

**Comment by nmtadam** [comment]
Line 70 is setting environment variables. Type 

```
$ luarocks path
```

and you should see some bash commands. eval then runs these commands.

**Pull request closed without merging**
